# Generated by Django 2.1.5 on 2019-02-08 18:40

from django.db import migrations


def add_candy(apps, schema_editor):
    Candy = apps.get_model('api', 'Candy')

    # snickers = Candy()
    # snickers.name = 'Snickers'
    # snickers.is_chocolate = True
    # snickers.save()

    Candy.objects.create(name='Bonbons', is_chocolate=True)
    Candy.objects.create(name='Bubble Gum', is_chocolate=False)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_candy),
    ]
